INSERT INTO `elemento`(`idelemento`,`nome`,`descricao`,`tipo_idtipo`) VALUES (10,' SENTIMENTO CAPRICHOSO',' Chegada Apresentador/Posic. Marujada/Bailados',1),
 (11,' SENSIBILIDADE',' (David Assayag)Acústico  Entrada Marujada e Bailado',1),
 (12,' CHAMADA DO BOI',' Entrada dos Modulos',1),
 (13,' CHEGADA DO MEU BOI',' Inicio Marujada/Posic. Modulos',1),
 (14,' TRILHA',' Texto Tema Exaltação Folclórica',1),
 (15,' ASA BRANCA,BOI DA LUA',' David Pout-Pourri',1),
 (16,' VIVA A CULTURA POPULAR',' Inic. Exaltação/Apar. Boi Caprichoso',1),
 (17,' RUFAR DO MEU TAMBOR',' Evolução do Boi/Aparição da Sinhazinha',1),
 (18,' ROSTINHO DE ANJO',' Evolução da Sinhazinha/Amo/Pai Francisco/Catirina e Gazumbá',1),
 (19,' 1º VERSO AMO',' Rock Cid ',1),
 (20,' VIVA A CULTURA POPULAR',' Toada Letra e Musica/Aparição Sinhazinha',1),
 (21,' 2º VERSO AMO',' Sinhazinha/Boi,Pai Francisco,Catirina e Gazumbá/Apar. Porta Estandarte',1),
 (22,' BALANÇO POPULAR',' Evolução da Porta Estandarte/Posic. Vaqueirada',1),
 (23,' VAQUEIROS DA FLORESTA 2x',' Evolução da Vaqueirada',1),
 (24,' UNIVERSO DE AMOR  ',' Montagem Fig. Tipica',1),
 (25,' 3º VERSO AMO',' Alusão ao tema da noite/Montagem Fig. Tipica',1),
 (26,' SENSIBILIDADE (David Assayag)',' Prep. Inicio Fig. Tipica',1),
 (27,' TRILHA',' Texto Figura Tipica Farinheiro',1),
 (28,' FARINHADA um de dois',' Evolução da Fig. Típica/Aparição da Rainha',1),
 (29,' FILHOS DA MUNDURUKÂNIA',' Evolução da Rainha',1),
 (30,' TRILHA',' Texto Lenda',1),
 (31,' EU SOU A LENDA um de dois',' Execução da Lenda /Aparição da Cunhã',1),
 (32,' CRIATURA DE TUPÃ',' Evolução da Cunhã/Saida da Lenda',1),
 (33,' GARRA DE MARUJEIRO',' Galera/Davi Lev. Toada/Saida da Lenda/Posic. Tribos',1),
 (34,' TRILHA',' Texto/Celebração Indígena',1),
 (35,' MAWACA',' Celebração Indígena',1),
 (36,' MÄI MARAKÄ',' Upuracê Tribal',1),
 (37,' LUZ DA COMULHÃO ',' Pajé e Tuxauas/Mont. Ritual',1),
 (38,' BALANÇO POPULAR',' Galera/Mont. Ritual',1),
 (39,' 5º VERSO AMO',' Oxente/Mont. Ritual',1),
 (40,' VIVA A CULTURA POPULAR',' Galera/Mont. Ritual',1),
 (41,' TRILHA',' Texto Ritual',1),
 (42,' MÄI MARAKÄ um de dois',' Evolução do Ritual/Cênica da Cunhã/Aparição do Pajé',1),
 (43,' NIRVANA XAMÂNICO',' Evolução do Pajé/saída do Ritual',1),
 (44,' A COR DO MEU PAÍS',' Galera/Saída do Ritual',1),
 (45,' 6º VERSO AMO',' Desafio Amo Contrário(um aparte deputado)Posic. Tribo Coreografada',1),
 (46,' TRILHA',' Texto upuraçê',1),
 (47,' MISTICA XINGUANA',' Tribo Coreografada/Pajé',1),
 (48,' SENTIMENTO CAPRICHOSO',' Saida do Modulo/Galera',1),
 (49,' VIVA A CULTURA POPULAR',' Encerramento',1);